### ISSUE TITLE
Integrating additional data sources to our system

### ISSUE THREAD

**Issue by Ignotus** [Ignotus/infoviz-project#9]
According to the intermediate tutorial there should be following types:
- cultural (museum/monuments/historical)
- green (parks/lakes/gardens)
- culinary (restaurants/coffees)
- sport (gyms/sport fields)
- relaxation (spas/saunas/massage salons)
- spiritual (churches/temples/shrines)
- activity (clubs/bars/dance halls/cinemas)

but now we have only two (green & sport)

**Comment by florisdb** [comment]
Done
